### ISSUE TITLE
kubernetes_events_monitor shouldn't filter event objects by default

### ISSUE THREAD

**Issue by schra** [scalyr/scalyr-agent-2#710]
What
----

The config `event_object_filter` of kubernetes_events_monitor filters the events by the resource type of their `involvedObject`.

I have three issues with this:

First, the documentation is wrong. It says "**If set,** only events whose `involvedObject` `kind` is on this list will be included.". But this is wrong. Events are filtered even if you didn't set the variable. In order to disable filtering you have to explicitly set `SCALYR_K8S_EVENT_OBJECT_FILTER=null`

This is the code I talk about https://github.com/scalyr/scalyr-agent-2/blob/81329c173634357092a963aad083583138f603ef/scalyr_agent/builtin_monitors/kubernetes_events_monitor.py#L134

Second, you should document that setting `SCALYR_K8S_EVENT_OBJECT_FILTER=null` disables the filtering.

Third, this goes against my expectation. My expectation is that *all* events are recorded to Scalyr by default. However, only events whose `involvedObject` is of type `'CronJob', 'DaemonSet', 'Deployment', 'Job', 'Node', 'Pod', 'ReplicaSet', 'ReplicationController', 'StatefulSet'` are recorded by default.

I only stumbled across this behavior by chance because an event regarding `Endpoints` wasn't recorded in Scalyr.

MWE
---

1. Do not override the default behavior of `event_object_filter` (do not set the `event_object_filter` config).

2. Create a file `event.yaml` with the following content:

  ```
  apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2021-01-21T12:14:00Z"
  involvedObject:
    kind: Endpoint
    name: kube-dns
    uid: kube-dns
  kind: Event
  metadata:
    creationTimestamp: "2021-01-21T12:17:11Z"
    name: event-foobar
  lastTimestamp: "2021-01-21T12:14:00Z"
  message: Foo bar!
  reason: FailedToCreateEndpoint
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: aks-default-26212293-vmss000000
  type: Normal
  ```

3. Execute

  ```
  kubectl apply -f event.yaml
  ```

4. Observe that you can see the event in K8s:

  ```
  $ kubectl get events event-foobar
  LAST SEEN   TYPE     REASON                   OBJECT              MESSAGE
  61m         Normal   FailedToCreateEndpoint   endpoint/kube-dns   Foo bar!
  ```

5. Observe that you cannot find the event in Scalyr

**Comment by weilliu** [comment]
@schra I did a quick test locally and I get the same result for your point 1 and 2. I will notify engineering to check it and potentially update the doc/code.

I will create a feature request for you on point 3. 

In your sample config file `events.yaml`, I think the issue is that you specify the kind of `involvedObject` to `Endpoint` rather than `Event`. Changing it to `Event` and adding `SCALYR_K8S_EVENT_OBJECT_FILTER: Event` should ingest the logs to Scalyr.
```
involvedObject:
  kind: Event
  name: kube-dns
  uid: kube-dns
```
